// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: does_user_exist.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const doesUserExist = `-- name: DoesUserExist :one
SELECT id FROM users WHERE id = $1
`

func (q *Queries) DoesUserExist(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, doesUserExist, id)
	err := row.Scan(&id)
	return id, err
}
