// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_user_from_refresh_token.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getSingleUserFromRefreshToken = `-- name: GetSingleUserFromRefreshToken :one

SELECT id, users.created_at, users.updated_at, email, hashed_password, token, refresh_tokens.created_at, refresh_tokens.updated_at, user_id, expires_at, revoked_at FROM users INNER JOIN refresh_tokens ON users.id = refresh_tokens.user_id WHERE refresh_tokens.token = $1
`

type GetSingleUserFromRefreshTokenRow struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	HashedPassword string
	Token          string
	CreatedAt_2    time.Time
	UpdatedAt_2    time.Time
	UserID         uuid.UUID
	ExpiresAt      sql.NullTime
	RevokedAt      sql.NullTime
}

func (q *Queries) GetSingleUserFromRefreshToken(ctx context.Context, token string) (GetSingleUserFromRefreshTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getSingleUserFromRefreshToken, token)
	var i GetSingleUserFromRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.Token,
		&i.CreatedAt_2,
		&i.UpdatedAt_2,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}
